In [1]:
# http://jupyter.org/widgets
# https://ipyleaflet.readthedocs.io/en/latest/api_reference/marker.html
# https://github.com/jupyter-widgets/ipyleaflet

from ipyleaflet import Map, CircleMarker, Marker, basemaps, basemap_to_tiles, Rectangle, Polygon

from pandas import DataFrame, read_csv
import pandas as pd

In [2]:
root_dir = '../..'

sensors_file = root_dir + '/Sample_Data/For_Modeling/sensor_gps_view.csv'
sensors = pd.read_csv(sensors_file, delimiter=';', decimal=',')

center = (sensors['longitude'].mean(), sensors['latitude'].mean())
sensors

   sensor_id  latitude  longitude
0       1074  5.794506  53.200509
1       1078  5.793081  53.200826
2       1079  5.797128  53.200347
3       1625  5.792219  53.199183
4       1627  5.793139  53.200104
5       1631  5.791639  53.202216
6       1636  5.796556  53.201777
7       2054  5.795879  53.199645
8       2779  5.799048  53.202032

In [3]:
import numpy as np

def arrow (p1, p2):
    y1, x1 = p1
    y2, x2 = p2

    # direction vector
    dx = x2 - x1
    dy = y2 - y1

    # normal vector
    nx = -dy
    ny = dx
    
    scale_y = .35
    dy = dy * scale_y
    ny = ny * scale_y
    
    return [
        (y1, x1),
        (y2, x2),
        (y2 + ny * 0.05,                         x2 + nx * 0.05),
        (y2 + ny * 0.05 + (ny + dy) * 0.01,      x2 + nx * 0.05 - (nx + dx) * 0.01),
#        (y1 + ny,                  x1 + nx),
#        (p2[0] + ny * 0.05 - (ny + dy) / 16, p2[1] + nx * 0.05 - (nx + dx) / 16)
    ]

In [4]:
m = Map(
    center=center,
    zoom=16
)

for index, row in sensors.iterrows():
    if index> 0:
        # print( index, row)
        form = (row.longitude, row.latitude)
        marker = Marker(location=form, draggable=False)
        m.add_layer(marker);
        for j, r in sensors.iterrows():
            if j>0 and j != index:
                to = (r.longitude, r.latitude)
                arrow(form, to)
                p = Polygon(
                    locations= arrow(form, to),
                    color="red",
                    fill_color="orange"
        
                )
                m.add_layer(p)
            break


m

Map(basemap={'url': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 'max_zoom': 19, 'attribution': 'Map â€¦

In [5]:
for i in range(20):
    a = arrow( center, (center[0]+0.002 * i/10, center[1]+0.003))

    p = Polygon(
        locations= a,
        color="red",
        fill_color="orange"
    )

    m.add_layer(p)

In [6]:
sensor_by_year_month_file = root_dir + '/Sample_Data/For_Modeling/sensorbyyearmonth_view.csv'

sensor_by_year_month = pd.read_csv(sensor_by_year_month_file, delimiter=',', decimal=',')
sensor_by_year_month

     VirtualSensorCode YearMonth  Aantal  longitude  latitude
0                 1074   2018-04  205244  53.200509  5.794506
1                 1074   2018-03  234933  53.200509  5.794506
2                 1074   2018-02  185492  53.200509  5.794506
3                 1074   2018-01  182631  53.200509  5.794506
4                 1074   2017-12  235459  53.200509  5.794506
5                 1074   2017-11  240476  53.200509  5.794506
6                 1074   2017-10  242991  53.200509  5.794506
7                 1074   2017-09  131607  53.200509  5.794506
8                 1074   2017-08  251232  53.200509  5.794506
9                 1074   2017-07  263216  53.200509  5.794506
10                1074   2017-06  225251  53.200509  5.794506
11                1074   2017-05  255209  53.200509  5.794506
12                1074   2017-04  242140  53.200509  5.794506
13                1074   2017-03  213294  53.200509  5.794506
14                1074   2017-02  173689  53.200509  5.794506
15                1074   2017-01  200275  53.200509  5.794506
16                1074   2016-12  254540  53.200509  5.794506
17                1074   2016-11  218999  53.200509  5.794506
18                1074   2016-10  243867  53.200509  5.794506
19                1074   2016-09  257039  53.200509  5.794506
20                1074   2016-08  263508  53.200509  5.794506
21                1074   2016-07  249709  53.200509  5.794506
22                1074   2016-06  188113  53.200509  5.794506
23                1074   2016-05  207109  53.200509  5.794506
24                1074   2016-04  203526  53.200509  5.794506
25                1074   2016-03  177958  53.200509  5.794506
26                1074   2016-02  159120  53.200509  5.794506
27                1074   2016-01  148098  53.200509  5.794506
28                1078   2018-04  126428  53.200826  5.793081
29                1078   2018-03  152665  53.200826  5.793081
..                 ...       ...     ...        ...       ...
203               2054   2017-05   87580  53.199645  5.795879
204               2054   2017-04   91256  53.199645  5.795879
205               2054   2017-03   82543  53.199645  5.795879
206               2054   2017-02   74364  53.199645  5.795879
207               2054   2017-01   81561  53.199645  5.795879
208               2054   2016-12   98551  53.199645  5.795879
209               2054   2016-11   86778  53.199645  5.795879
210               2054   2016-10   89587  53.199645  5.795879
211               2054   2016-09   76813  53.199645  5.795879
212               2054   2016-08   77165  53.199645  5.795879
213               2054   2016-07   80798  53.199645  5.795879
214               2054   2016-06   71864  53.199645  5.795879
215               2054   2016-05   75202  53.199645  5.795879
216               2054   2016-04   38247  53.199645  5.795879
217               2779   2018-04   94695  53.202032  5.799048
218               2779   2018-03  112547  53.202032  5.799048
219               2779   2018-02   96360  53.202032  5.799048
220               2779   2018-01  107532  53.202032  5.799048
221               2779   2017-12  134095  53.202032  5.799048
222               2779   2017-11  147130  53.202032  5.799048
223               2779   2017-10  145164  53.202032  5.799048
224               2779   2017-09  132472  53.202032  5.799048
225               2779   2017-08  106354  53.202032  5.799048
226               2779   2017-07  145210  53.202032  5.799048
227               2779   2017-06  143896  53.202032  5.799048
228               2779   2017-05  159481  53.202032  5.799048
229               2779   2017-04   97157  53.202032  5.799048
230               2779   2017-03   41439  53.202032  5.799048
231               2779   2017-02    1101  53.202032  5.799048
232               2779   2016-11      31  53.202032  5.799048

[233 rows x 5 columns]

In [7]:
# TODO: how to make a crosstab

# pd.crosstab(sensor_by_year_month,sensor_by_year_month['Aantal'])

In [8]:
sensor_by_year_month.mean()
mean = sensor_by_year_month['Aantal'].max()
mean

263508

In [9]:
scale_x = 20000
scale_y = 1250
middle = -15
aantal_max = sensor_by_year_month['Aantal'].max()

for index, row in sensor_by_year_month.iterrows():
    if index> 0:
        # print( index, row)
        #marker = CircleMarker(location=(row.longitude, row.latitude), radius=30, color='red', fill_color='red')
        #m.add_layer(marker);
        
        ym = row.YearMonth
        
        year, month = ym.split('-')
        year = int(year)
        month = int(month)
        d_year = year - 2016
        d_year
        month

        idx = middle + d_year *12 + (month -1)
        idx
        
        x = idx / scale_x
        x2 = (idx + 0.2) / scale_x
        
        y = row.Aantal / aantal_max / scale_y
        
        #print (idx, row.longitude, row.latitude, row.Aantal)
        rectangle = Rectangle(color="red"
                             , bounds=((row.longitude, row.latitude + x), (row.longitude+ y, row.latitude + x2)))
        m.add_layer(rectangle)

m

Map(basemap={'url': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 'max_zoom': 19, 'attribution': 'Map â€¦